version: '3.9'
name: 'nest-chat-api'

services:
  app:
    build: .
    ports:
      - '2000:2000'
    depends_on:
      - postgres_server

  postgres_server:
    image: postgres:14-alpine
    ports:
      - 1000:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=nestChat
      - POSTGRES_DB=nestChat

volumes:
  postgres_data:
