# Use the official Node.js image as the base image
FROM node:18

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json (or yarn.lock) to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY . .

RUN npx prisma generate
RUN npx prisma migrate dev

# Build the NestJS application
RUN npm run build

# Expose the application port
EXPOSE 2000

# Define the command to run the application
CMD ["npm", "run", "start:dev"]